### ISSUE TITLE
Are 100 extra_ids enough for {"type": "X", "mean_noise_span_length": 3, "noise_density":0.5} denoiser

### ISSUE THREAD

**Issue by chenxu001** [OpenNLG/OpenBA#2]
max_seq_length = 1024
noise tokens = max_seq_length * noise_density = 512
span counts = noise tokens / mean_noise_span_length ≈ 171
are 100 extra_ids enough ?

**Comment by ZetangForward** [comment]
Thank you for your interest in OpenBA. In the first stage, we apply **three different denoising strategies to each sequence**. The S-denoiser occupies 1/4 of the text length. The mean noise span lengths for the X-denoiser are a combination of {3, 8, 64}, and we sample the mean noise span length uniformly. Thus, 100 extra_ids is **enough for masking each sequence**.

You can refer to https://github.com/OpenNLG/OpenBA/blob/b9d180be21a94083c0b66825419d0f031ea3f9cc/training/megatron/data/t5_dataset.py#L22-L30 for more details.
