### ISSUE TITLE
如何获取数据集

### ISSUE THREAD

**Issue by MattMaBX** [OpenNLG/OpenBA#3]
请问如何获得OpenBA模型训练所需的数据集呢

**Comment by ZetangForward** [comment]
您好，感谢关注OpenBA，考虑各方面因素，我们没有直接放出BiFlan的数据，而是在论文附录中提供了BiFlan的构建数据集链接以及每条数据的格式（请参考Appendix B，Table14）。您可以根据论文中的细节自己构建。至于预训练数据，我们采用了开源 + 部分可获取的数据进行构建，清洗方案请参考论文Section 3.1。
