### ISSUE TITLE
咨询一下你们的邮箱账号

### ISSUE THREAD

**Issue by Oneiro7** [OpenNLG/OpenBA#4]
可以把你们的邮箱账号公开一下吗，准备试用一下你们的模型，十分感谢！

**Comment by ZetangForward** [comment]
您好，我们的模型已开源到Huggingface上：[https://huggingface.co/OpenBA](https://huggingface.co/OpenBA) 您可以直接使用。论文的主要作者的邮箱已写在技术报告中：[https://arxiv.org/abs/2309.10706](https://arxiv.org/abs/2309.10706)。欢迎提供使用建议。
